name: GitHub-Profile-3D-Contrib

on:
  schedule:           # todo dia Ã s 18:00 UTC (03:00 JST)
    - cron: "0 18 * * *"
  workflow_dispatch:  # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2

      # Gera os arquivos 3D na pasta profile-3d-contrib
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      # Comita e faz push das alteraÃ§Ãµes
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A profile-3d-contrib
          git commit -m "ðŸ”§ generated 3D contrib"
          git push
